version: '3'
services:
  db:
    image: postgres
    ports:
      - "5432"
  backend:
    build:
      context: auth-test-backend
      args:
        UID: ${UID:-1001}
    volumes:
      - ./auth-test-backend:/usr/src/app
    ports:
      - "3001:3001"
    depends_on:
      - db
    user: rails
  frontend:
    build:
      context: auth-test-frontend
      args:
        UID: ${UID:-1001}
    volumes:
      - ./auth-test-frontend:/usr/src/app
    ports:
      - "3000:3000"
    user: frontend